version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: axon-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: axon_user
      POSTGRES_PASSWORD: axon_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - axon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axon_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: axon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - axon-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  axon-network:
    driver: bridge